name: aksinfra

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TF_WORKING_DIR: ./env/dev/
  STORAGE_RG: "satya-rg"
  STORAGE_ACCOUNT: "satyastoghf"
  CONTAINER_NAME: "container"
  STATE_FILE: "aksinfra.tfstate"

jobs:
  aksinfra:
    name: Create AKS Infrastructure
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ env.STORAGE_RG }}" \
            -backend-config="storage_account_name=${{ env.STORAGE_ACCOUNT }}" \
            -backend-config="container_name=${{ env.CONTAINER_NAME }}" \
            -backend-config="key=${{ env.STATE_FILE }}"

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate
        
      - name: Terraform Refresh
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -refresh-only -auto-approve

      # - name: Terraform Plan
      #   working-directory: ${{ env.TF_WORKING_DIR }}
      #   run: terraform plan -out=tfplan || true

      # - name: Terraform Apply
      #   if: github.ref == 'refs/heads/main'
      #   working-directory: ${{ env.TF_WORKING_DIR }}
      #   run: terraform apply -auto-approve tfplan || true

      - name: Check if Plan Has Changes
        working-directory: ${{ env.TF_WORKING_DIR }}
        id: plan
        run: |
          terraform plan -out=tfplan
          terraform show -json tfplan | jq '.resource_changes | length' > changes.txt
          echo "::set-output name=changes::$(cat changes.txt)"
      
      - name: Terraform Apply if Changes Exist
        if: steps.plan.outputs.changes != '0'
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve tfplan


